//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecapMvcApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageBlogTable
    {
        public int EntryId { get; set; }
        public int BlogId { get; set; }
        public string ImageUrl { get; set; }
    
        public virtual Blog Blog { get; set; }
    }
}
