//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecapMvcApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyTable
    {
        public int PropertyId { get; set; }
        public string PropertyOwner { get; set; }
        public string PropertyAddress { get; set; }
        public int PropertyTypeId { get; set; }
        public string PropertyStatus { get; set; }
    
        public virtual PropertyTypeTable PropertyTypeTable { get; set; }
    }
}
